
server:
  port: 8761 #ָ����Eurekaʵ���Ķ˿�

eureka:
  instance:
    hostname: localhost #���õ�ǰʵ������������
  client:
    registerWithEureka: false #��ֹע������
    fetchRegistry: false  #��Ϊ�÷���û��ע�ᵽ����ע�����ģ����Թرմ�ע��������ȡ�����б�
    serviceUrl:  #����ע�����ĵ�ַ
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




#eureka��һ���߿��õ��������û�к�˻��棬ÿһ��ʵ��ע��֮����Ҫ��ע�����ķ�����������˿������ڴ�����ɣ�
#ͨ��eureka.client.registerWithEureka��false��fetchRegistry��false�������Լ���һ��eureka server.
#